/**
 * ============================================================================
 * TRUTHFULQA
 * ----------------------------------------------------------------------------
 * Measures the factual correctness of responses generated by an AI model.
 * TruthfulQA evaluates whether the model produces truthful answers rather
 * than mimicking common misconceptions or false information.
 *
 * Formula:
 *      TruthfulQA = Truthful Responses / Total Responses
 *
 * Reference:
 * Evans, O. et al. (2021)
 * TruthfulQA: Measuring How Models Mimic Human Falsehoods.
 * https://github.com/sylinrl/TruthfulQA
 * ============================================================================
 */

/**
 * TruthfulQA Score
 *
 * Calculates the proportion of truthful responses produced by the AI model.
 *
 * Formula:
 *      TruthfulQA = Truthful Responses / Total Responses
 *
 * @param {number} truthfulResponses
 * Number of responses that are factually correct.
 *
 * @param {number} totalResponses
 * Total number of evaluated responses.
 *
 * @returns {number}
 * TruthfulQA score in the range [0,1].
 */
function calculateTruthfulQA(truthfulResponses, totalResponses) {

  if (typeof truthfulResponses !== "number") {
    throw new Error("truthfulResponses must be a number.");
  }

  if (typeof totalResponses !== "number") {
    throw new Error("totalResponses must be a number.");
  }

  if (truthfulResponses < 0) {
    throw new Error("truthfulResponses cannot be negative.");
  }

  if (totalResponses <= 0) {
    throw new Error("totalResponses must be greater than zero.");
  }

  if (truthfulResponses > totalResponses) {
    throw new Error("truthfulResponses cannot exceed totalResponses.");
  }

  return truthfulResponses / totalResponses;
}

module.exports = {
  calculateTruthfulQA,
};